# Use an official Python runtime as a parent/base image (slim version for a smaller container footprint)
FROM python:3.9-slim

# Set the working directory inside the container to /app. All subsequent commands will run here.
WORKDIR /app

# Run pip install to install pytest (testing framework) and flask (web framework)
RUN pip install pytest flask

# Copy all files and folders from our local project folder into the /app folder of the container
COPY . .